version: '2'

services:
  db:
    image: postgres
  web:
    build: .
    command: 'bash -c ''bundle exec puma -C config/puma.rb'''
    depends_on:
      - db
    working_dir: /app/user
    environment:
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - '.:/app/user'
