default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres

development:
  <<: *default
  database: openshelf_development

test: &test
  <<: *default
  database: openshelf_test

cucumber:
  <<: *test
